service: sample-serverless-framework-python
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1
  stackName: sample-serverless-framework-python

functions:
  simple-function:
    name: sample-serverless-framework-python
    description: The is sample function.
    handler: lambda_function.lambda_handler
    memorySize: 128
    timeout: 5
    environment:
      SAMPLE_VALUE: ${env:SAMPLE_VALUE}
    tags:
      Name: sample-serverless-framework-python
      Env: ${env:ENV}
      Owner: nago3
      Service: sample
      ServerlessFramework: "True"
