service: sample-serverless-framework-python
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1

functions:
  simple-function:
    handler: lambda_function.lambda_handler
    environment:
      SAMPLE_VALUE: ${env:SAMPLE_VALUE}
